---
- hosts: all
  become: yes
      
  roles:
  - role: action-allow-ssh-password-authentication
  - role: action-timezone
    vars:
      timezone_name: Asia/Taipei
  - role: docker-redis
    vars:
      version: 5.0