Vagrant.configure("2") do |config|

  config.vm.define "ubuntu-1604" do |machine|
    machine.vm.box = "ubuntu/xenial64"    
	machine.vm.network "private_network", ip: "192.168.1.11"	
  end
 
  config.vm.synced_folder "../../provision", "/provision"
  
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = true
    vb.cpus = 1
    # Customize the amount of memory on the VM:
    vb.memory = "1048"
  end
  
  config.vm.provision "ansible_local" do |ansible|
    ansible.provisioning_path = "/provision"
    ansible.playbook = "redis-5.0-provision.yml"    
  end
end